services:
  caddy:
    image: ghcr.io/justforjan/my-home-page
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy-config:/config
      - caddy-data:/data

volumes:
  caddy-config:
  caddy-data:

