services:
  caddy:
    image: !reset null
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEPLOYMENT_TYPE: local # either local or prod. Must also be set in GitHub Pipeline so that the correct Caddyfile gets selected
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy-config-local:/config
      - caddy-data-local:/data
    environment:
      API_BASE_URL: https:\\localhost:8000

  backend:
    image: !reset null
    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      RUNNING_LOCALLY: True
    develop:
      watch:
        - action: sync
          path: ./backend/app/
          target: ./backend/app/
        - action: sync
          path: ./backend/main.py
          target: ./backend/main.py
        - action: rebuild
          path: ./backend
          ignore:
            - ./backend/main.py
            - ./backend/app/


volumes:
  caddy-config-local:
  caddy-data-local: