services:
  caddy:
    image: ghcr.io/justforjan/my-home-page_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy-config:/config
      - caddy-data:/data
    environment:
      API_BASE_URL: https:\\api.justforjan.eu
      RUNNING_IN_DOCKER: True

  backend:
    image: ghcr.io/justforjan/my-home-page_backend
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - backend/.env
    environment:
      RUNNING_IN_DOCKER: True
      RUNNING_LOCALLY: False


  database:
    image: postgres:alpine
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - backend/.env

  minio:
    image: quay.io/minio/minio:latest
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - backend/.env
    command: server /data --console-address ":9001"



volumes:
  caddy-config:
  caddy-data:
  database:
  minio_data:

