services:
  caddy:
    image: ghcr.io/justforjan/my-home-page
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy-config:/config
      - caddy-data:/data
    environment:
      RUNNING_IN_DOCKER: True

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - backend/.env
    environment:
      RUNNING_IN_DOCKER: True
      RUNNING_LOCALLY: False


  database:
    image: postgres:alpine
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - backend/.env


volumes:
  caddy-config:
  caddy-data:
  database:

