services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - caddy-config:/config
      - caddy-data:/data


volumes:
  caddy-config:
  caddy-data:

