services:
  caddy:
    image: !reset null
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy-config-local:/config
      - caddy-data-local:/data
    environment:
      DOMAIN_WEBSITE: localhost
      DOMAIN_API: localhost:8000

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - backend/.env
    environment:
      RUNNING_IN_DOCKER: True
    develop:
      watch:
        - action: sync
          path: ./backend/app/
          target: ./backend/app/
        - action: sync
          path: ./backend/main.py
          target: ./backend/main.py
        - action: rebuild
          path: ./backend
          ignore:
            - ./backend/main.py
            - ./backend/app/



  database:
    image: postgres:alpine
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - backend/.env


volumes:
  caddy-config:
  caddy-data:
  database:

