services:
  website-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - ./.env
    environment:
      RUNNING_IN_DOCKER : True
    develop:
      watch:
        - action: sync
          path: ./app/
          target: ./backend/app/
        - action: sync
          path: ./main.py
          target: ./backend/main.py
        - action: rebuild
          path: .
          ignore:
            - ./backend/main.py
            - ./backend/app/

  database:
    image: postgres:alpine
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}


volumes:
  database:
