name: Common Checkout Setup
on:
  workflow_call:

env:
  GITHUB_REGISTRY: ghcr.io

jobs:
  setup:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v4

      - name: Log into Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_ACCESS_TOKEN }}


